name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test:unit

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    # Skip E2E tests if secrets are not configured
    if: ${{ secrets.APPWRITE_ENDPOINT != '' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      
      - name: Create .env file
        run: |
          echo "APPWRITE_ENDPOINT=${{ secrets.APPWRITE_ENDPOINT }}" >> .env
          echo "APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }}" >> .env
          echo "APPWRITE_DATABASE_ID=${{ secrets.APPWRITE_DATABASE_ID }}" >> .env
          echo "APPWRITE_API_KEY=${{ secrets.APPWRITE_API_KEY }}" >> .env
          echo "VITE_APPWRITE_ENDPOINT=${{ secrets.APPWRITE_ENDPOINT }}" >> .env
          echo "VITE_APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }}" >> .env
          echo "VITE_APPWRITE_DATABASE_ID=${{ secrets.APPWRITE_DATABASE_ID }}" >> .env
          echo "VITE_APPWRITE_API_KEY=${{ secrets.APPWRITE_API_KEY }}" >> .env
          echo "VITE_YOUTUBE_API_KEY=${{ secrets.VITE_YOUTUBE_API_KEY }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "VITE_JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      
      - name: Run E2E tests
        run: npm run test:e2e
        continue-on-error: true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build all apps
        run: npm run build
        env:
          VITE_APPWRITE_ENDPOINT: https://placeholder.appwrite.io/v1
          VITE_APPWRITE_PROJECT_ID: placeholder
          VITE_APPWRITE_DATABASE_ID: placeholder
          VITE_JWT_SECRET: placeholder
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: apps/*/dist
          retention-days: 7
